vich_uploader:
    db_driver: orm

    mappings:
        post:
            uri_prefix: '%app.path.post%'
            upload_destination: '%kernel.project_dir%/public/images/blog'
        products:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
